
```mermaid
graph TD
   subgraph 分析对象["分析对象"]
   输入音节[音节] 
   end

   subgraph 质调分层["音节分成节调与节质两层"]
   输入音节 --> 节调[节调: 音节的音调]
   输入音节 --> 节质[节质: 音节的音质]
   end

   subgraph 音节的音调["节调分成首调和干调两段"]
   节调 --> 首调[首调: 首音的音调]
   节调 --> 干调[干调: 干音的音调]
   end

   subgraph 音节的音质["节质分成声母和韵母两段"]
   节质 --> 声母[声母: 首音的音质]
   节质 --> 韵母[韵母: 干音的音质]
   end

   subgraph 首音构成["首音由首调与声母构成"]
   首调 --> 输入首音[首音]
   声母 --> 输入首音[首音]
   end

   subgraph 干音构成["干音由干调与韵母构成"]
   干调 --> 输入干音[干音]
   韵母 --> 输入干音[干音]
   end

   subgraph 干音类型["干音根据韵母结构类型分成四类"]
   输入干音 --> 三质干音[三质干音]
   输入干音 --> 前长干音[前长干音]
   输入干音 --> 后长干音[后长干音]
   输入干音 --> 单质干音[单质干音]
   end

   subgraph 单质干音分析流程["单质干音分析流程"]

   单质干音 --> 单质干音音调[干音音调]
   单质干音音调 --> 单质干音韵调[韵调]
   单质干音音调 --> 单质干音呼调[呼调]
   单质干音韵调 --> 单质干音主调[主调]
   单质干音韵调 --> 单质干音末调[末调]

   单质干音 --> 单质干音音质[单质韵母]
   单质干音音质 --> 单质干音韵质[韵质]
   单质干音音质 --> 单质干音呼质[韵母前段]
   单质干音韵质 --> 单质干音主质[韵母中段]
   单质干音韵质 --> 单质干音末质[韵母后段]

   end

   subgraph 后长干音分析流程["后长干音分析流程"]

   后长干音 --> 后长干音音质[后长韵母]
   后长干音音质 --> 后长干音呼质[韵头]
   后长干音音质 --> 后长干音韵质[韵腹]
   后长干音韵质 --> 后长干音主质[韵腹前段]
   后长干音韵质 --> 后长干音末质[韵腹后段]

   后长干音 --> 后长干音音调[干音音调]
   后长干音音调 --> 后长干音呼调[呼调]
   后长干音音调 --> 后长干音韵调[韵调]
   后长干音韵调 --> 后长干音主调[主调]
   后长干音韵调 --> 后长干音末调[末调]
   end

   subgraph 前长干音分析流程["前长干音分析流程"]

   前长干音 --> 前长干音音质[前长韵母]
   前长干音音质 --> 前长干音间质[韵腹]
   前长干音间质 --> 前长干音呼质[韵腹前段]
   前长干音间质 --> 前长干音主质[韵腹后段]
   前长干音音质 --> 前长干音末质[韵尾]

   前长干音 --> 前长干音音调[干音音调]
   前长干音音调 --> 前长干音间调[间调]
   前长干音间调 --> 前长干音呼调[呼调]
   前长干音间调 --> 前长干音主调[主调]
   前长干音音调 --> 前长干音末调[末调]
   end

   subgraph 三质干音分析流程["三质干音分析流程"]
   三质干音 --> 三质干音音质[三质韵母]
   三质干音音质 --> 三质干音呼质[韵头]
   三质干音音质 --> 三质干音韵质[韵质]
   三质干音韵质 --> 三质干音主质[韵腹]
   三质干音韵质 --> 三质干音末质[韵尾]

   三质干音 --> 三质干音音调[干音音调]
   三质干音音调 --> 三质干音呼调[呼调]
   三质干音音调 --> 三质干音韵调[韵调]
   三质干音韵调 --> 三质干音主调[主调]
   三质干音韵调 --> 三质干音末调[末调]
   end

   单质干音呼调 --> 呼音[呼音]
   单质干音呼质 --> 呼音[呼音]
   单质干音主调 --> 主音[主音]
   单质干音主质 --> 主音[主音]
   单质干音末调 --> 末音[末音]
   单质干音末质 --> 末音[末音]

   后长干音呼调 --> 呼音[呼音]
   后长干音呼质 --> 呼音[呼音]
   后长干音主调 --> 主音[主音]
   后长干音主质 --> 主音[主音]
   后长干音末调 --> 末音[末音]
   后长干音末质 --> 末音[末音]

   前长干音呼调 --> 呼音[呼音]
   前长干音呼质 --> 呼音[呼音]
   前长干音主调 --> 主音[主音]
   前长干音主质 --> 主音[主音]
   前长干音末调 --> 末音[末音]
   前长干音末质 --> 末音[末音]

   三质干音呼调 --> 呼音[呼音]
   三质干音呼质 --> 呼音[呼音]
   三质干音主调 --> 主音[主音]
   三质干音主质 --> 主音[主音]
   三质干音末调 --> 末音[末音]
   三质干音末质 --> 末音[末音]

   subgraph 音元分析["音元分析法的音节结构模型"]
   主音 --> 韵音[韵音]
   末音 --> 韵音[韵音]
   呼音 --> 韵音层呼音[呼音] --> 干音[干音]
   韵音 --> 干音[干音]
   输入首音 --> 首音[首音] --> 韵音层首音[首音] --> 干音层首音[首音] --> 音节[音节]
   干音 --> 音节[音节]
   end
```
