from __future__ import annotations

import argparse
import csv
import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _decomposition_keys(path: Path) -> set[str]:
    with path.open(encoding="utf-8", newline="") as stream:
        return {
            str(row.get("pinyin_tone") or "").strip()
            for row in csv.DictReader(stream, delimiter="\t")
            if str(row.get("pinyin_tone") or "").strip()
        }


def _normalized_keys(path: Path) -> set[str]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"normalized pinyin asset must be a JSON object: {path}")
    return {str(key).strip() for key in payload if str(key).strip()}


def _pua_pinyin_keys(path: Path) -> set[str]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"PUA pinyin asset must be a JSON object: {path}")

    keys: set[str] = set()
    for values in payload.values():
        if not isinstance(values, list):
            raise ValueError(f"PUA pinyin values must be arrays: {path}")
        keys.update(str(value).strip() for value in values if str(value).strip())
    return keys


def _pinyin_code_keys(path: Path) -> set[str]:
    with path.open(encoding="utf-8", newline="") as stream:
        return {
            str(row.get("pinyin_tone") or "").strip()
            for row in csv.DictReader(stream, delimiter="\t")
            if str(row.get("pinyin_tone") or "").strip()
        }


def _asset_record(
    source: Path,
    destination: Path,
    entry_count: int,
    repo_root: Path,
) -> dict[str, object]:
    return {
        "name": destination.name,
        "source": source.relative_to(repo_root).as_posix(),
        "entry_count": entry_count,
        "bytes": destination.stat().st_size,
        "sha256": _sha256(destination),
    }


def prepare_assets(output_dir: Path, *, repo_root: Path = REPO_ROOT) -> dict[str, object]:
    output_dir.mkdir(parents=True, exist_ok=True)

    decomposition_source = repo_root / "internal_data" / "yime_syllable_decomposition.tsv"
    normalized_source = repo_root / "yime" / "pinyin_normalized.json"
    pua_source = repo_root / "yime" / "code_pinyin.json"
    pinyin_codes = output_dir / "yime_pinyin_codes.tsv"

    required = (decomposition_source, normalized_source, pua_source, pinyin_codes)
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise FileNotFoundError("required handoff assets are missing: " + ", ".join(missing))

    decomposition_keys = _decomposition_keys(decomposition_source)
    normalized_keys = _normalized_keys(normalized_source)
    pua_keys = _pua_pinyin_keys(pua_source)
    if decomposition_keys != normalized_keys or normalized_keys != pua_keys:
        raise ValueError(
            "auxiliary pinyin inventories disagree: "
            f"decomposition={len(decomposition_keys)}, "
            f"normalized={len(normalized_keys)}, pua={len(pua_keys)}"
        )

    code_keys = _pinyin_code_keys(pinyin_codes)
    unexpected_code_keys = sorted(code_keys - normalized_keys)
    if unexpected_code_keys:
        raise ValueError(
            "layout-code export contains pinyin absent from audited assets: "
            + ", ".join(unexpected_code_keys)
        )

    destinations = {
        decomposition_source: output_dir / "yime_syllable_decomposition.tsv",
        normalized_source: output_dir / "pinyin_normalized.json",
        pua_source: output_dir / "yime_pua_pinyin.json",
    }
    for source, destination in destinations.items():
        shutil.copy2(source, destination)

    inventory_count = len(normalized_keys)
    assets = [
        _asset_record(source, destination, inventory_count, repo_root)
        for source, destination in destinations.items()
    ]
    assets.append(
        {
            "name": pinyin_codes.name,
            "source": "generated by yime/export_rime_yime.py",
            "entry_count": len(code_keys),
            "bytes": pinyin_codes.stat().st_size,
            "sha256": _sha256(pinyin_codes),
        }
    )

    manifest: dict[str, object] = {
        "schema_version": "windows-yime-handoff-v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "audited_pinyin_inventory_count": inventory_count,
        "layout_code_inventory_count": len(code_keys),
        "audited_pinyin_without_layout_code": sorted(normalized_keys - code_keys),
        "assets": assets,
    }
    manifest_path = output_dir / "yime_handoff_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Copy and validate the complete auxiliary asset set for Windows Yime."
    )
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args()

    output_dir = Path(args.output_dir).resolve()
    manifest = prepare_assets(output_dir)
    print(f"auxiliary assets: {manifest['audited_pinyin_inventory_count']} audited pinyin rows")
    print(f"handoff manifest: {output_dir / 'yime_handoff_manifest.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
