graph TB
    A[音节] --> |分类|B[节——调<br>声母韵腹]
    A --> |分类|C[节————调<br>声母韵头韵腹]
    A --> |分类|D[节————调<br>声母韵腹韵尾]
    A --> |分类|E[节——————调<br>声母韵头韵腹韵尾]
    B --> |提取|F1[首调<br>声母]
    B --> |提取|G1[呼调<br>呼质]
    B --> |提取|H1[主调<br>主质]
    B --> |提取|I1[末调<br>末质]
    subgraph " "
    C --> |提取|F2[首调<br>声母]
    C --> |提取|G2[呼调<br>呼质]
    C --> |提取|H2[主调<br>主质]
    C --> |提取|I2[末调<br>末质]
    end
    subgraph " "
    D --> |提取|F3[首调<br>声母]
    D --> |提取|G3[呼调<br>呼质]
    D --> |提取|H3[主调<br>主质]
    D --> |提取|I3[末调<br>末质]
    end
    E --> |提取|F4[首调<br>声母]
    E --> |提取|G4[呼调<br>呼质]
    E --> |提取|H4[主调<br>主质]
    E --> |提取|I4[末调<br>末质]
    F1 --> |构成|N[首音]
    G1 --> |构成|O[呼音]
    H1 --> |构成|P[主音]
    I1 --> |构成|Q[末音]
    F2 --> |构成|N[首音]
    G2 --> |构成|O[呼音]
    H2 --> |构成|P[主音]
    I2 --> |构成|Q[末音]
    F3 --> |构成|N[首音]
    G3 --> |构成|O[呼音]
    H3 --> |构成|P[主音]
    I3 --> |构成|Q[末音]
    F4 --> |构成|N[首音]
    G4 --> |构成|O[呼音]
    H4 --> |构成|P[主音]
    I4 --> |构成|Q[末音]

    N --> |构成|R[音节]
    O --> |构成|R
    P --> |构成|R
    Q --> |构成|R

