


graph TB
    A[音节] -----> |提取|B[节调]
    A --> |提取|C[节质]
    C --> |切分|D[声质]
    C ----> |切分|E[韵质]
    D --> |分类|F[单纯声质]
    D --> |分类|G[首介声质]
    F --> |又分析为|H[声母]
    G --> |切分|I[声母]
    G --> |切分|J[介质]

