
graph TB
    A[音节] --> |当韵母是韵质时|B[第一类音节]
    A --> |当韵母非韵质时|C[第二类音节]

    B --> |提取|D[节调]
    B --> |提取|E[节质]

    C --> |提取|F[节调]
    C --> |提取|G[节质]

    D --> H[节调]
    E --> |切分|I[声母]
    E --> |切分|J[唯韵韵母]

    F --> K[节调]
    G --> |切分|L[声母]
    G --> |切分|M[介韵韵母]

    H --> N[节调]
    I --> O[声质]
    J --> P[韵质]

    K --> Q[节调]
    L --> R[声质]
    M --> |切分|S[介质]
    M --> |切分|T[韵质]


