graph TB
    Start((开始)) --> A[干音]
    A --> |提取|B[干调]
    A --> |提取|C[韵母]
    C --> |切分|D[介质]
    C --> |切分|E[韵质]
    D --> |改名|F[韵头]
    E --> |切分|G[韵腹]
    E --> |切分|H[韵尾]
    F --> |改名|I[呼质]
    G --> |改名|J[主质]
    H --> |改名|L[末质]
    B --> |切分|M[呼调]
    B --> |切分|N[韵调]
    N --> |传递|O[韵调]

    M --> |传递|P[呼调]
    P --> |传递|Q[呼调]

    O -->  |切分|R[主调]
    O -->  |切分|S[末调]

    Q -->  |构成|T[呼音]
    I -->  |构成|T
    R -->  |构成|U[主音]
    J -->  |构成|U
    S -->  |构成|V[末音]
    L -->  |构成|V
    T -->  |构成|W[干音]
    U -->  |构成|W
    V -->  |构成|W
    W --> End((结束))
