graph TB
    Start((开始)) --> A[干音]
    A --> |提取|B[干调]
    A --> |提取|C[韵母]
    C --> |切分|D[介质]
    C --> |切分|E[韵质]
    D --> |又被分析成为|F[韵头]
    F --> |改名|F1[呼质]
    E --> |切分|G[韵腹]
    G --> |改名|G1[主质]
    E --> |切分|H[韵尾]
    H --> |改名|H1[末质]
    B --> |切分|I[呼调]
    B --> |切分|J[韵调]
    J --> |代入|J1[韵调]

    I --> |代入|I1[呼调]
    J1 -->  |切分|L[主调]
    J1 -->  |切分|M[末调]

    I1 --> |代入|I2[呼调]

    I2 -->  |构成|N[呼音]
    F1 -->  |构成|N
    L -->  |构成|O[主音]
    G1 -->  |构成|O
    M -->  |构成|P[末音]
    H1 -->  |构成|P
    N -->  |构成|Q[干音]
    O -->  |构成|Q
    P -->  |构成|Q
    Q --> End((结束))
