graph BT
I[i] --- IOU((●))
O[ɤ] --- IOU((●))
U[u] --- IOU((●))

IOU ---  B((●))
B ---  B1[5]

IOU ---  C((●))
C ---  C1[3]
C ---  C2[5]

IOU ---  D((●))
D ---  D1[2]
D --- D2[1]
D --- D3[4]

IOU ---  E((●))
E ---  E1[5]
E --- E2[1]

classDef plain fill:none,stroke:none;
class I,O,U,IOU,B,C,D,E,B1,C1,C2,D1,D2,D3,E1,E2,Title plain;

