graph BT

U[u] --- UO((●))
O[o] --- UO((●))

UO ---  B((●))
B ---  B1[5]

UO ---  C((●))
C ---  C1[3]
C ---  C2[5]

UO ---  D((●))
D ---  D1[2]
D --- D2[1]
D --- D3[4]

UO ---  E((●))
E ---  E1[5]
E --- E2[1]

classDef plain fill:none,stroke:none;
class U,O,UO,B,C,D,E,B1,C1,C2,D1,D2,D3,E1,E2,Title plain;

