graph TB
    A[音节] --> |分类|B[节——调<br>声母韵腹]
    A --> |分类|C[节————调<br>声母韵头韵腹]
    A --> |分类|D[节————调<br>声母韵腹韵尾]
    A --> |分类|E[节——————调<br>声母韵头韵腹韵尾]
    B --> |切分|N[首音]
    B --> |切分|O[呼音]
    B --> |切分|P[主音]
    B --> |切分|Q[末音]
    C --> |切分|N[首音]
    C --> |切分|O[呼音]
    C --> |切分|P[主音]
    C --> |切分|Q[末音]
    D --> |切分|N[首音]
    D --> |切分|O[呼音]
    D --> |切分|P[主音]
    D --> |切分|Q[末音]
    E --> |切分|N[首音]
    E --> |切分|O[呼音]
    E --> |切分|P[主音]
    E --> |切分|Q[末音]
    subgraph " "
    N
    O
    P
    Q
    end


