graph TB
    Start((开始)) --> A[干音]
    A --> |提取|B[干调]
    A --> |提取|C[韵母]
    C --> |切分|D[韵腹]
    C --> |切分|E[韵尾]
    D --> |切分|F[韵腹前段]
    D --> |切分|G[韵腹后段]
    F --> |改名|H[呼质]
    G --> |改名|I[主质]
    E --> J[韵尾]
    J --> |改名|K[末质]
    B --> |切分|L[间调]
    B --> |切分|M[末调]
    L -->  |切分|N[呼调]
    L -->  |切分|O[主调]
    M -->  |切分|P[末调]
    subgraph 构成[ ]
    N -->  |构成|Q[呼音]
    H -->  |构成|Q
    O -->  |构成|R[主音]
    I -->  |构成|R
    P -->  |构成|S[末音]
    K -->  |构成|S
    end
    Q -->  |构成|T[干音]
    R -->  |构成|T
    S -->  |构成|T
    T --> End((结束))
