graph TB
    Start((开始)) --> A[干音]
    A --> |提取|B[干调]
    A --> |提取|C[韵母]

    B --> |切分|D1[呼调]
    B --> |切分|D2[韵调]
    D1 --> |代入|D3[呼调]
    D2 --> |代入|D4[韵调]
    D3 --> |代入|D5[呼调]
    D4 --> |切分|D6[主调]
    D4 --> |切分|D7[末调]
    D5 --> |代入|D8[呼调]
    D6 -->  |代入|P[主调]
    D7 -->  |代入|Q[末调]

    C --> |切分|E[介质]
    C --> |切分|F[韵质]

    E --> |又被分析成为|E1[韵头]
    E1 --> |代入|E2[韵头]
    E2 --> |改名|E3[呼质]

    F --> |又被分析成为|G[韵腹]
    G --> |切分|I[韵腹前段]
    G --> |切分|J[韵腹后段]
    I --> |改名|L[主质]
    J --> |改名|M[末质]

    D8 --> |构成|N3[呼音]
    E3 --> |构成|N3
    P -->  |构成|S[主音]
    L -->  |构成|S
    Q -->  |构成|T[末音]
    M -->  |构成|T
    N3 -->  |构成|U[干音]
    S -->  |构成|U
    T -->  |构成|U
    U --> End((结束))
