graph TB
    Start((开始)) --> A[干音]
    A --> |提取|B[干调]
    A --> |提取|C[韵母]
    C --> |切分|D[介质]
    C --> |切分|E[韵质]
    D --> |改名|F[韵头]
    E --> |改名|G[韵腹]
    F --> H[韵头]
    G --> |切分|I[韵腹前段]
    G --> |切分|J[韵腹后段]
    H --> |改名|K[呼质]
    I --> |改名|L[主质]
    J --> |改名|M[末质]
    B --> |切分|N[呼调]
    B --> |切分|O[韵调]
    O -->  |切分|P[主调]
    O -->  |切分|Q[末调]

    N -->  |构成|R[呼音]
    K -->  |构成|R
    P -->  |构成|S[主音]
    L -->  |构成|S
    Q -->  |构成|T[末音]
    M -->  |构成|T
    R -->  |构成|U[干音]
    S -->  |构成|U
    T -->  |构成|U
    U --> End((结束))
