graph TB
    Start((开始)) --> |输入|A[音节]
    subgraph 提取节调和节质[" "]
        A --> |提取音节的音调|A1[节调<br>声调]
        A --> |提取音节的音质|A2[节质<br>声母+韵母]
    end

    subgraph 切分节调和节质[" "]
        A1 --> |提取首音的音调|D1[首调<br>与声母联结的调段]
        A1 --> |提取干音的音调|D2[干调<br>与韵母联结的调段]
        A2 --> |切分首音的音质|C1[首质<br>声母]
        A2 --> |切分干音的音质|C2[干质<br>韵母]
    end

    subgraph 切分首音和干音[" "]
            D1 --> |构成|F[首音]
            C1 --> |构成|F
            D2 --> |构成|G[干音]
            C2 --> |构成|G
    end

    subgraph 首音和干音分类[" "]
        F --> |分类|F0{有无辨义作用}
        F0 --> |有|F1[实首音]
        F0 --> |无|F2[虚首音]
        G --> |分类|G0{何类韵母类型}
        G0 --> |三质韵母|G1[三质干音]
        G0 --> |前长韵母|G2[前长干音]
        G0 --> |后长韵母|G3[后长干音]
        G0 --> |单质韵母|G4[单质干音]
    end

    subgraph 分析首音和干音[" "]

        subgraph 首音分析[" "]
            subgraph 实首音[" "]
                F1 --> |提取| H0[音调]
                F1 --> |提取| H1[音质]
                H0 --> |非区别特征| H4
                H1 --> |区别特征| H4[非零声母]
            end
            subgraph 虚首音[" "]
                F2 --> |提取| H2[音调]
                F2 --> |提取| H3[音质]
                H2 --> |非区别特征| H5
                H3 --> |非区别特征| H5[零声母]
            end
            H4 --> |统称|H6[声母]
            H5 --> |统称|H6
        end

        subgraph 单质[" "]
        G4 --> |提取|J1[干调]
            subgraph 单质韵母[" "]
                G4 --> |提取|J2[单质韵母]
                J2 --> |又被分析成为|J3[韵基]
                J3 --> |又被分析成为|J4[韵腹]
            end
        end

        subgraph 后长[" "]
        G3 --> |提取|K1[干调]
            subgraph 后长韵母[" "]
                G3 --> |提取|K2[后长韵母]
                K2 --> |切分|K3[韵头]
                K2 --> |切分|K4[韵基]
                K4 --> |又被分析成为|K5[韵腹]
            end
        end

        subgraph 前长[" "]
        G2 --> |提取|L0[干调]
            subgraph 前长韵母[" "]
                G2 --> |提取|L3[前长韵母]
                L3 --> |又被分析成为|L4[韵基]
                L4 --> |切分|L5[韵腹]
                L4 --> |切分|L6[韵尾]
            end
        end

        subgraph 三质[" "]
        G1 --> |提取|M0[干调]
            subgraph 三质韵母[" "]
                G1 --> |提取|M1[三质韵母]
                M1 --> |切分|M2[韵头]
                M1 --> |切分|M3[韵基]
                M3 --> |切分|M4[韵腹]
                M3 --> |切分|M5[韵尾]
            end
        end

    end

    K1 --> |切分|K6[呼调]
    K1 --> |切分|K7[韵调]

    L0 --> |切分|L1[间调]
    L0 --> |切分|L2[末调]

    M0 --> |切分|M6[呼调]
    M0 --> |切分|M7[主调]
    M0 --> |切分|M8[末调]

    subgraph 唱音分析[" "]
        subgraph 充当首音的唱音[" "]
            H6 --> |从形式上提取|H7[首调]
            H6 --> |从形式上提取|H8[首质]
            H7 --> |构成|H9
            H8 --> |构成|H9[首音]
        end
        subgraph 构成干音的唱音[" "]
            J1 --> |构成|N1[单质干音]
            J4 --> |构成|N1
            N1 --> |简称|N2[干音]

            K6 --> |构成|O1[介音]
            K3 --> |构成|O1
            K7 --> |构成|O2[韵音]
            K5 --> |构成|O2

            L1 --> |构成|P1[间音]
            L5 --> |构成|P1
            L2 --> |构成|P2[尾音]
            L6 --> |构成|P2

            M6 --> |构成|Q1[介音]
            M2 --> |构成|Q1
            M7 --> |构成|Q2[主音]
            M4 --> |构成|Q2
            M8 --> |构成|Q3[尾音]
            M5 --> |构成|Q3
        end
    end

    subgraph 音节层次结构模型[" "]
        H9 --> |升级|R0[首音]
        R0 --> |升级|R1[首音]

        N2 --> |升级|R2[单质干音]

        O1 --> |构成|R3
        O2 --> |构成|R3[后长干音]

        P1 --> |构成|R4
        P2 --> |构成|R4[前长干音]

        Q1 --> |构成|R5
        Q2 --> |构成|R5
        Q3 --> |构成|R5[三质干音]

        R2  --> |统称|R6[干音]
        R3  --> |统称|R6
        R4  --> |统称|R6
        R5  --> |统称|R6


        R1 --> |构成|S
        R6 --> |构成|S[音节]
    end
    S --> |输出|End((结束))
