graph TB
    Start((开始)) --> |输入|A[音节]
        A --> |提取音节的音调|B[节调<br>声调]
        A --> |提取音节的音质|C[节质<br>声母+韵母]

        B --> |提取首音的音调|D1[首调<br>与声母联结的调段]
        B --> |提取干音的音调|D2[干调<br>与韵母联结的调段]
        C --> |提取首音的音质|C1[首质<br>声母]
        C --> |提取干音的音质|C2[干质<br>韵母]

        D1 --> |构成|F[首音]
        C1 --> |构成|F
        D2 --> |构成|G[干音]
        C2 --> |构成|G

        F --> |分类|F0{有无是否对立}
        F0 --> |是|F1[实首音]
        F0 --> |否|F2[虚首音]

        G --> |分类|G0{韵母是何类型}
        G0 --> |单质韵母|G1[单质干音]
        G0 --> |后长韵母|G2[后长干音]
        G0 --> |前长韵母|G3[前长干音]
        G0 --> |三质韵母|G4[三质干音]

        F1 --> |实质| H1[非零声母]
        F2 --> |实质| H2[零声母]
        H1 --> |提取| H3[音调]
        H1 --> |提取| H4[音质]
        H2 --> |提取| H5[音调]
        H2 --> |提取| H6[音质]
        H3 --> |合并| H7
        H5 --> |合并| H7[首调]
        H4 --> |合并| H8
        H6 --> |合并| H8[首质]
        H8 --> |构成|H9
        H7 --> |构成|H9[首音]

        G1 --> |提取|J0[干调]
        G1 --> |提取|J3[单质韵母]
        J0 --> |代入|J1[干调]
        J3 --> |又被分析成为|J4[韵基]
        J1 --> |代入|J2[干调]
        J4 --> |又被分析成为|J5[韵腹]

        G2 --> |提取|K0[干调]
        K0 --> |切分|K1[呼调]
        K0 --> |切分|K2[韵调]
        G2 --> |提取|K3[后长韵母]
        K1 --> |代入|K7[呼调]
        K2 --> |代入|K8[韵调]
        K3 --> |切分|K9[介质]
        K3 --> |切分|K5[韵基]
        K9 --> |改名|K4[韵头]
        K5 --> |又被分析成为|K6[韵腹]

        G3 --> |提取|L0[干调]
        G3 --> |提取|L4[前长韵母]
        L0 --> |代入|L1[干调]
        L1 --> |切分|L2[间调]
        L1 --> |切分|L3[末调]
        L4 --> |又被分析成为|L5[韵基]
        L5 --> |切分|L6[韵腹]
        L5 --> |切分|L7[韵尾]

        G4 --> |提取|M0[干调]
        M0 --> |切分|M01[呼调]
        M0 --> |切分|M02[韵调]
        M01 --> |代入|M1[呼调]
        M02 --> |切分|M2[主调]
        M02 --> |切分|M3[末调]
        G4 --> |提取|M4[三质韵母]
        M4 --> |切分|M5[介质]
        M4 --> |切分|M6[韵基]
        M5 --> |改名|M7[韵头]
        M6 --> |切分|M8[韵腹]
        M6 --> |切分|M9[韵尾]

        J2 --> |构成|N1[干音]
        J5 --> |构成|N1

        K7 --> |构成|O1[介音]
        K4 --> |构成|O1
        K8 --> |构成|O2[韵音]
        K6 --> |构成|O2

        L2 --> |构成|P1[间音]
        L6 --> |构成|P1
        L3 --> |构成|P2[尾音]
        L7 --> |构成|P2

        M1 --> |构成|Q1[介音]
        M7 --> |构成|Q1
        M2 --> |构成|Q2[主音]
        M8 --> |构成|Q2
        M3 --> |构成|Q3[尾音]
        M9 --> |构成|Q3

        H9 --> |升级|R0[首音]
        R0 --> |升级|R1[首音]

        N1 --> |分类|R2[单质干音]

        O1 --> |构成|R3
        O2 --> |构成|R3[后长干音]

        P1 --> |构成|R4
        P2 --> |构成|R4[前长干音]

        Q1 --> |构成|R5
        Q2 --> |构成|R5
        Q3 --> |构成|R5[三质干音]

        R2  --> |统称|R6[干音]
        R3  --> |统称|R6
        R4  --> |统称|R6
        R5  --> |统称|R6

        R1 --> |构成|S
        R6 --> |构成|S[音节]
    S --> |输出|End((结束))
