graph TB
    A[音节] --> B[首音干音]
    B --> C[声——调<br>声母韵母]
    C --> E[声————调<br>声母唯韵韵质]
    C --> F[声————调<br>声母介质韵质]

    E --> G[声————调<br>声母单质韵母]
    E --> H[声————调<br>声母前长韵母]
    F --> I[声————调<br>声母后长韵母]
    F --> J[声————调<br>声母三质韵母]

    G ---> G1[首音]
    H ---> G1[首音]
    I ---> G1[首音]
    J ---> G1[首音]

    G ---> G2[呼音]
    H ---> G2[呼音]
    I ---> G2[呼音]
    J ---> G2[呼音]

    G ---> G3[主音]
    H ---> G3[主音]
    I ---> G3[主音]
    J ---> G3[主音]

    G ---> G4[末音]
    H ---> G4[末音]
    I ---> G4[末音]
    J ---> G4[末音]

G1 --> K[音节]
G2 --> K[音节]
G3 --> K[音节]
G4 --> K[音节]

