graph TB
    A[音——节] --> B[首音干音]
    B --> C[声——调<br>声母韵母]
    C --> E[声————调<br>声母唯韵韵质]
    C --> F[声————调<br>声母介质韵质]

    E --> G[声————调<br>声母单质韵母]
    E --> H[声————调<br>声母前长韵母]
    F --> I[声————调<br>声母后长韵母]
    F --> J[声————调<br>声母三质韵母]

    G --> G1[首音]
    G --> G2[呼音]
    G --> G3[主音]
    G --> G4[末音]
    H --> H1[首音]
    H --> H2[呼音]
    H --> H3[主音]
    H --> H4[末音]
    I --> I1[首音]
    I --> I2[呼音]
    I --> I3[主音]
    I --> I4[末音]
    J --> J1[首音]
    J --> J2[呼音]
    J --> J3[主音]
    J --> J4[末音]


