graph TB
    A[音节] --> B[首音干音]
    B --> C[声——调<br>声母韵母]
    C --> E[声————调<br>声母无介韵母]
    C --> F[声————调<br>声母有介韵母]

    E --> G[声————调<br>声母单质韵母]
    E --> H[声————调<br>声母前长韵母]
    F --> I[声————调<br>声母后长韵母]
    F --> J[声————调<br>声母三质韵母]

    G ---> |第一类音节|G1[首音]
    H ---> |第二类音节|G1[首音]
    I ---> |第三类音节|G1[首音]
    J ---> |第四类音节|G1[首音]

    G ---> |第一类音节|G2[呼音]
    H ---> |第二类音节|G2[呼音]
    I ---> |第三类音节|G2[呼音]
    J ---> |第四类音节|G2[呼音]

    G ---> |第一类音节|G3[主音]
    H ---> |第二类音节|G3[主音]
    I ---> |第三类音节|G3[主音]
    J ---> |第四类音节|G3[主音]

    G ---> |第一类音节|G4[末音]
    H ---> |第二类音节|G4[末音]
    I ---> |第三类音节|G4[末音]
    J ---> |第四类音节|G4[末音]


