graph TB
A[节质]  --- |分类|B1[声母韵腹型]
A --- |分类|B2[声母韵腹韵尾型]
A --- |分类|B3[声母韵头韵腹型]
A --- |分类|B4[声母韵头韵腹韵尾型]

B1 --- |切分|C1[声母]
B1 --- |切分|C2[韵母]
C2 --- |又分析为|C3[韵基]
C3 --- |又分析为|C4[韵腹]

B2 --- |切分|D1[声母]
B2 --- |切分|D2[韵母]
D2 --- |又分析为|D3[韵基]
D3 --- |切分|D4[韵腹]
D3 --- |切分|D5[韵尾]

B3 --- |切分|E1[声母]
B3 --- |切分|E2[韵母]
E2 --- |切分|E3[韵头]
E2 --- |切分|E4[韵基]
E4 --- |又分析为|E5[韵腹]

B4 --- |切分|F1[声母]
B4 --- |切分|F2[韵母]
F2 --- |切分|F3[韵头]
F2 --- |切分|F4[韵基]
F4 --- |切分|F5[韵腹]
F4 --- |切分|F6[韵尾]

