graph TB
A[节质]  --- |分类|B1[声母韵腹型]
A --- |分类|B2[声母韵腹韵尾型]
A --- |分类|B3[声母韵头韵腹型]
A --- |分类|B4[声母韵头韵腹韵尾型]
B1 --- |切分|C1[声母]
B1 --- |切分|C2[韵腹]
B2 --- |切分|D1[声母]
B2 --- |切分|D2[韵腹]
B2 --- |切分|D3[韵尾]
B3 --- |切分|E1[声母]
B3 --- |切分|E2[韵头]
B3 --- |切分|E3[韵腹]
B4 --- |切分|F1[声母]
B4 --- |切分|F2[韵头]
B4 --- |切分|F3[韵腹]
B4 --- |切分|F4[韵尾]
