graph TB
A[节质]  --- |切分|B[声质]
A --- |切分|C[韵质]

B --- |分类|D[单纯声质]
B --- |分类|E[首介声质]

C --- |分类|F[单纯韵质]
C --- |分类|G[复合韵质]

D --- |又分析为|H[声母]
E --- |切分|I[声母]
E --- |切分|J[介质]

F --- |又分析为|K[韵核]
G --- |切分|L[韵核]
G --- |切分|M[韵尾]
