graph TB
    A[音节] --> |当韵母是单质韵母时|A1[第一类音节]
    A[音节] --> |当韵母是前长韵母时|A2[第二类音节]
    A[音节] --> |当韵母是后长韵母时|A3[第三类音节]
    A[音节] --> |当韵母是三质韵母时|A4[第四类音节]

    A1 --> |提取|B1[节调]
    A2 --> |提取|B2[节调]
    A3 --> |提取|B3[节调]
    A4 --> |提取|B4[节调]


    A1 --> |提取|C1[节质]
    A2 --> |提取|C2[节质]
    A3 --> |提取|C3[节质]
    A4 --> |提取|C4[节质]

    C1 --> |切分|D1[声母]
    C2 --> |切分|D2[声母]
    C3 --> |切分|D3[声母]
    C4 --> |切分|D4[声母]

    C1 --> |切分|E1[韵母]
    C2 --> |切分|E2[韵母]
    C3 --> |切分|E3[韵母]
    C4 --> |切分|E4[韵母]

    E1 --> F1[韵基]
    F1 --> F2[韵腹]

    E2 --> |分类|G1[韵基]
    G1 --> |分类|G2[韵腹]
    G1 --> |分类|G3[韵尾]

    E3 --> |切分|H1[韵头]
    E3 --> |分类|H2[韵基]
    H2 --> |分类|H3[韵腹]

    E4 --> |切分|I1[韵头]
    E4 --> |切分|I2[韵基]
    I2 --> |切分|I3[韵腹]
    I2 --> |切分|I4[韵尾]
