graph TB
    A[音节] --> |提取|B[节调]
    A --> |提取|C[节质]
    C --> |切分|D[声母]
    C --> |切分|E[韵母]
    E --> |分类|F[唯韵韵母]
    E --> |分类|G[介韵韵母]
    F --> |又分析为|H[韵质]
    G --> |切分|I[介质]
    G --> |切分|J[韵质]
    H --> |分类|K[单质韵质]
    H --> |分类|L[复合韵质]
    J --> |分类|M[单质韵质]
    J --> |分类|N[复合韵质]
    I --> |传递|O[介质]
    I --> |传递|P[介质]
    subgraph 三质韵母[三质韵母]
        P --> |又分析为|Q[韵头]
        N --> |切分|R[韵腹]
        N --> |切分|S[韵尾]
    end
    subgraph 前长韵母[后长韵母]
        O --> |又分析为|T[韵头]
        M --> |又分析为|U[韵腹]
    end
    subgraph 后长韵母[前长韵母]
        L --> |切分|V[韵腹]
        L --> |切分|W[韵尾]
    end
    subgraph 单质韵母[单质韵母]
        K --> |又分析为|X[韵腹]
    end

