graph TB
    A[音节] --> B[节调]
    A --> C[节质]
    C --> D[声母]
    C --> E[韵母]
    E --> F{是否韵质}
    F --> |是|G[干韵韵母]
    G --> H[韵质]
    F --> |否|I[介韵韵母]
    I --> J[介质]
    I --> K[韵质]
    H --> H1{是否单质}
    H1 --> |是|L[单质韵质]
    H1 --> |否|M[复质韵质]
    K --> K0{是否单质}
    K0 --> |是|N[单质韵质]
    K0 --> |否|O[复质韵质]
    J --> U[介质]
    J --> V[介质]
    subgraph 韵母[ ]
        subgraph 单质韵母[单质韵母]
            L --> P[韵腹]
        end
        subgraph 前长韵母[前长韵母]
            M --> Q[韵腹]
            M --> R[韵尾]
        end
        subgraph 后长韵母[后长韵母]
            V --> S[韵头]
            N --> T[韵腹]
        end
        subgraph 三质韵母[三质韵母]
            U --> W[韵头]
            O --> X[韵腹]
            O --> Y[韵尾]
        end
    end
