graph TB
    A[音节] --> B[节————调<br>声母单质韵母]
    A --> C[节————调<br>声母后长韵母]
    A --> D[节————调<br>声母前长韵母]
    A --> E[节————调<br>声母三质韵母]
    B --> B1[首音]
    B --> B2[呼音]
    B --> B3[主音]
    B --> B4[末音]
    C --> C1[首音]
    C --> C2[呼音]
    C --> C3[主音]
    C --> C4[末音]
    D --> D1[首音]
    D --> D2[呼音]
    D --> D3[主音]
    D --> D4[末音]
    E --> E1[首音]
    E --> E2[呼音]
    E --> E3[主音]
    E --> E4[末音]

