graph TB
    A[音节] --> B[节————调<br>声母单质韵母]
    A --> C[节————调<br>声母后长韵母]
    A --> D[节————调<br>声母前长韵母]
    A --> E[节————调<br>声母三质韵母]

    B ---> |第一类音节|F[首音]
    C ---> |第二类音节| F[首音]
    D ---> |第三类音节| F[首音]
    E ---> |第三类音节| F[首音]

    B ---> |第一类音节|G[呼音]
    C ---> |第二类音节| G[呼音]
    D ---> |第三类音节| G[呼音]
    E ---> |第三类音节| G[呼音]

    B ---> |第一类音节|H[主音]
    C ---> |第二类音节| H[主音]
    D ---> |第三类音节| H[主音]
    E ---> |第三类音节| H[主音]

    B ---> |第一类音节|I[末音]
    C ---> |第二类音节| I[末音]
    D ---> |第三类音节| I[末音]
    E ---> |第三类音节| I[末音]
