graph TB
    Start((开始)) --> |输入|A[音节]
        A --> |提取音节的音调|B[节调<br>声调]
        A --> |提取音节的音质|C[节质<br>声母+韵母]

        B --> |提取首音的音调|D1[首调<br>与声母联结的调段]
        B --> |提取干音的音调|D2[干调<br>与韵母联结的调段]
        C --> |切分首音的音质|E1[首质<br>声母]
        C --> |切分干音的音质|E2[干质<br>韵母]

        D1 --> |构成|F[首音]
        E1 --> |构成|F
        D2 --> |构成|G[干音]
        E2 --> |构成|G

        F --> |分类|F0{有无是否对立}
        F0 --> |是|F1[实首音]
        F0 --> |否|F2[虚首音]
        F1 --> |实质| F3[非零声母]
        F2 --> |实质| F4[零声母]

        F3 --> |提取| H1[音调]
        F3 --> |提取| H2[音质]
        F4 --> |提取| H3[音调]
        F4 --> |提取| H4[音质]
        H1 --> |统称| H5
        H3 --> |统称| H5[首音音调]
        H2 --> |统称| H6
        H4 --> |统称| H6[首音音质]
        H5 --> |简称| H7[首调]
        H6 --> |简称| H8[首质]
        H7 --> |构成|H9
        H8 --> |构成|H9[噪音]

        G --> |分类|G0{韵母是何类型}
        G0 --> |三质韵母|G1[三质干音]
        G0 --> |前长韵母|G2[前长干音]
        G0 --> |后长韵母|G3[后长干音]
        G0 --> |单质韵母|G4[单质干音]

        G4 --> |提取|J[干调]
        J --> |传递|J1[干调]
        J1 --> |切分|J2[呼调]
        J1 --> |切分|J3[主调]
        J1 --> |切分|J4[末调]
        J2 --> |传递|J21[呼调]
        J3 --> |传递|J31[主调]
        J4 --> |传递|J41[末调]
        G4 --> |提取|J5[单质韵母]
        J5 --> |又分析为|J6[韵腹]
        J6 --> |切分|J61[韵母前段]
        J6 --> |切分|J62[韵母中段]
        J6 --> |切分|J63[韵母后段]

        G3 --> |提取|K0[干调]
        K0 --> |切分|K1[呼调]
        K0 --> |切分|K2[韵调]
        K1 --> |传递|K3[呼调]
        K2 --> |切分|K21[主调]
        K2 --> |切分|K22[末调]
        K3 --> |传递|K31[呼调]
        K21 --> |传递|K32[主调]
        K22 --> |传递|K33[末调]
        G3 --> |提取|K4[后长韵母]
        K4 --> |切分|K5[韵头]
        K4 --> |切分|K6[韵腹]
        K5 --> |传递|K51[韵头]
        K6 --> |切分|K61[韵质前段]
        K6 --> |切分|K62[韵质后段]

        G2 --> |提取|L1[干调]
        L1 --> |切分|L11[间调]
        L1 --> |切分|L12[末调]
        L11 --> |切分|L2[呼调]
        L11 --> |切分|L3[主调]
        L12 --> |传递|L32[末调]
        L2 --> |传递|L20[呼调]
        L3 --> |传递|L31[主调]
        L32 --> |传递|L33[末调]

        G2 --> |提取|L4[前长韵母]
        L4 --> |切分|L5[韵腹]
        L4 --> |切分|L6[韵尾]
        L5 --> |切分|L51[韵腹前段]
        L5 --> |切分|L52[韵腹后段]
        L6 --> |传递|L61[韵尾]

        G1 --> |提取|M0[干调]
        M0 --> |切分|M1[呼调]
        M0 --> |切分|M2[韵调]
        M1 --> |传递|M10[呼调]
        M2 --> |切分|M21[主调]
        M2 --> |切分|M22[末调]
        M10 --> |传递|M11[呼调]
        M21 --> |传递|M211[主调]
        M22 --> |传递|M31[末调]
        G1 --> |提取|M4[三质韵母]
        M4 --> |切分|M5[介质]
        M5 --> |改名|M51[韵头]
        M4 --> |切分|M6[韵基]
        M6 --> |切分|M61[韵腹]
        M6 --> |切分|M62[韵尾]

        J61 --> |改名|J7[呼质]
        J62 --> |改名|J8[主质]
        J63 --> |改名|J9[末质]
        K51 --> |改名|K7[呼质]
        K61 --> |改名|K8[主质]
        K62 --> |改名|K9[末质]
        L51 --> |改名|L7[呼质]
        L52 --> |改名|L8[主质]
        L61 --> |改名|L9[末质]
        M51 --> |改名|M7[呼质]
        M61 --> |改名|M8[主质]
        M62 --> |改名|M9[末质]

        J21 --> |构成|N2[乐音]
        J7 --> |构成|N2
        J31 --> |构成|N3[乐音]
        J8 --> |构成|N3
        J41 --> |构成|N4[乐音]
        J9 --> |构成|N4

        K31 --> |构成|O1[乐音]
        K7 --> |构成|O1
        K32 --> |构成|O2[乐音]
        K8 --> |构成|O2
        K33 --> |构成|O3[乐音]
        K9 --> |构成|O3

        L20 --> |构成|P1[乐音]
        L7 --> |构成|P1
        L31 --> |构成|P2[乐音]
        L8 --> |构成|P2
        L33 --> |构成|P3[乐音]
        L9 --> |构成|P3

        M11 --> |构成|Q1[乐音]
        M7 --> |构成|Q1
        M211 --> |构成|Q2[乐音]
        M8 --> |构成|Q2
        M31 --> |构成|Q3[乐音]
        M9 --> |构成|Q3

        H9 --> |充当首音|R1[首音]
        N2 --> |充当呼音|R2[呼音]
        N3 --> |充当主音|R3[主音]
        N4 --> |充当末音|R4[末音]

        O1 --> |充当呼音|R2
        O2 --> |充当主音|R3
        O3 --> |充当末音|R4

        P1 --> |充当呼音|R2
        P2 --> |充当主音|R3
        P3 --> |充当末音|R4

        Q1 --> |充当呼音|R2
        Q2 --> |充当主音|R3
        Q3 --> |充当末音|R4

        R1 --> |传递|S1[首音]
        R2 --> |传递|S2[呼音]
        R3 --> |构成|S3[韵音]
        R4 --> |构成|S3

        S1 --> |传递|T1[首音]
        S2 --> |构成|T2[干音]
        S3 --> |构成|T2

        T1 --> |构成|U1[音节]
        T2 --> |构成|U1
    U1 --> |输出|End((结束))

